theme: jekyll-theme-cayman

lang: zh-CN
title: VPN 推荐指南
description: VPN 推荐与使用指南（测评与选购建议）

timezone: Asia/Shanghai
logo: /assets/images/logo.jpeg

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

url: https://vpn4ai.github.io
baseurl: ""

collections:
  posts:
    output: true
    permalink: /posts/:name/

adsense_enabled: false
adsense_client: ""

go_defaults:
  strongvpn: "https://strongvpn.com"
  purevpn: "https://billing.purevpn.com/aff.php?aff=49387327"
  surfshark: "https://surfshark.com"
  nordvpn: "https://nordvpn.com"
  expressvpn: "https://www.expressvpn.com"
  cyberghost: "https://www.cyberghostvpn.com"
  pia: "https://www.privateinternetaccess.com"
  protonvpn: "https://protonvpn.com"
  mullvad: "https://mullvad.net"
  atlas: "https://atlasvpn.com"
  ivacy: "https://www.ivacy.com"
